name: Deploy Javadoc to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Javadoc
        run: ./gradlew javadoc

      - name: Fix Javadoc paths
        run: |
          find ./build/docs/javadoc -type f -name "*.html" -exec sed -i 's|href="javadoc/stylesheet.css|href="css/stylesheet.css|g' {} \;
          find ./build/docs/javadoc -type f -name "*.html" -exec sed -i 's|href="javadoc/script-dir/jquery-ui.min.css|href="css/jquery-ui.min.css|g' {} \;

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/javadoc
          enable_jekyll: false
